# -*- coding: utf-8 -*-
"""tworotor_240825.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GO881IvMO1SG51c1j_nBJTfS_wsoDoF_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Frequency of Two Rotor
def tworotor(L,Ia,Ib,ds,G):
  pi=math.pi
  J=(pi*ds**4)/32
  la=(Ib/(Ia+Ib))*L
  lb=(Ia/(Ia+Ib))*L
  fna=(1/(2*pi))*math.sqrt((G*J)/(Ia*la))
  fnb=(1/(2*pi))*(G*J/(Ib*lb))**0.5
  return fna

"""[link text](https://) https://github.com/ankuransaha/Torsional-Vibration-of-Shafts.git"""